// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: services/data_ingestion.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tradingbot.data_ingestion";

export interface GetMarketDataBarsRequest {
  /** Internal instrument identifier. */
  instrumentId: string;
  /** Kline interval, e.g. "1m", "5m", "1h". */
  interval: string;
  /** Start of the time range (Unix epoch milliseconds, inclusive). */
  fromMs: number;
  /** End of the time range (Unix epoch milliseconds, inclusive). */
  toMs: number;
  /** Maximum number of bars to return. 0 means server default (500). */
  limit: number;
}

export interface GetMarketDataBarsResponse {
  bars: MarketDataBarRecord[];
}

/** MarketDataBarRecord is the read-model projection stored in TimescaleDB. */
export interface MarketDataBarRecord {
  instrumentId: string;
  symbol: string;
  venue: string;
  interval: string;
  openTimeMs: number;
  closeTimeMs: number;
  open: string;
  high: string;
  low: string;
  close: string;
  volume: string;
  quoteVolume: string;
  tradeCount: number;
}

function createBaseGetMarketDataBarsRequest(): GetMarketDataBarsRequest {
  return { instrumentId: "", interval: "", fromMs: 0, toMs: 0, limit: 0 };
}

export const GetMarketDataBarsRequest: MessageFns<GetMarketDataBarsRequest> = {
  encode(message: GetMarketDataBarsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrumentId !== "") {
      writer.uint32(10).string(message.instrumentId);
    }
    if (message.interval !== "") {
      writer.uint32(18).string(message.interval);
    }
    if (message.fromMs !== 0) {
      writer.uint32(24).int64(message.fromMs);
    }
    if (message.toMs !== 0) {
      writer.uint32(32).int64(message.toMs);
    }
    if (message.limit !== 0) {
      writer.uint32(40).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMarketDataBarsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMarketDataBarsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.interval = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.fromMs = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.toMs = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetMarketDataBarsRequest>, I>>(base?: I): GetMarketDataBarsRequest {
    return GetMarketDataBarsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMarketDataBarsRequest>, I>>(object: I): GetMarketDataBarsRequest {
    const message = createBaseGetMarketDataBarsRequest();
    message.instrumentId = object.instrumentId ?? "";
    message.interval = object.interval ?? "";
    message.fromMs = object.fromMs ?? 0;
    message.toMs = object.toMs ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetMarketDataBarsResponse(): GetMarketDataBarsResponse {
  return { bars: [] };
}

export const GetMarketDataBarsResponse: MessageFns<GetMarketDataBarsResponse> = {
  encode(message: GetMarketDataBarsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.bars) {
      MarketDataBarRecord.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMarketDataBarsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMarketDataBarsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bars.push(MarketDataBarRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetMarketDataBarsResponse>, I>>(base?: I): GetMarketDataBarsResponse {
    return GetMarketDataBarsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMarketDataBarsResponse>, I>>(object: I): GetMarketDataBarsResponse {
    const message = createBaseGetMarketDataBarsResponse();
    message.bars = object.bars?.map((e) => MarketDataBarRecord.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMarketDataBarRecord(): MarketDataBarRecord {
  return {
    instrumentId: "",
    symbol: "",
    venue: "",
    interval: "",
    openTimeMs: 0,
    closeTimeMs: 0,
    open: "",
    high: "",
    low: "",
    close: "",
    volume: "",
    quoteVolume: "",
    tradeCount: 0,
  };
}

export const MarketDataBarRecord: MessageFns<MarketDataBarRecord> = {
  encode(message: MarketDataBarRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrumentId !== "") {
      writer.uint32(10).string(message.instrumentId);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(26).string(message.venue);
    }
    if (message.interval !== "") {
      writer.uint32(34).string(message.interval);
    }
    if (message.openTimeMs !== 0) {
      writer.uint32(40).int64(message.openTimeMs);
    }
    if (message.closeTimeMs !== 0) {
      writer.uint32(48).int64(message.closeTimeMs);
    }
    if (message.open !== "") {
      writer.uint32(58).string(message.open);
    }
    if (message.high !== "") {
      writer.uint32(66).string(message.high);
    }
    if (message.low !== "") {
      writer.uint32(74).string(message.low);
    }
    if (message.close !== "") {
      writer.uint32(82).string(message.close);
    }
    if (message.volume !== "") {
      writer.uint32(90).string(message.volume);
    }
    if (message.quoteVolume !== "") {
      writer.uint32(98).string(message.quoteVolume);
    }
    if (message.tradeCount !== 0) {
      writer.uint32(104).int64(message.tradeCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDataBarRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDataBarRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.interval = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.openTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.closeTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.open = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.high = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.low = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.close = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.volume = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.quoteVolume = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.tradeCount = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MarketDataBarRecord>, I>>(base?: I): MarketDataBarRecord {
    return MarketDataBarRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketDataBarRecord>, I>>(object: I): MarketDataBarRecord {
    const message = createBaseMarketDataBarRecord();
    message.instrumentId = object.instrumentId ?? "";
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.interval = object.interval ?? "";
    message.openTimeMs = object.openTimeMs ?? 0;
    message.closeTimeMs = object.closeTimeMs ?? 0;
    message.open = object.open ?? "";
    message.high = object.high ?? "";
    message.low = object.low ?? "";
    message.close = object.close ?? "";
    message.volume = object.volume ?? "";
    message.quoteVolume = object.quoteVolume ?? "";
    message.tradeCount = object.tradeCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
