// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v7.34.1
// source: services/execution_engine.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SignalSide } from "../common/signal";
import { OrderStatus } from "../events/events";

export const protobufPackage = "tradingbot.execution_engine";

export interface ListPortfolioExecutionOrdersRequest {
  portfolioId: string;
  limit: number;
}

export interface ListPortfolioExecutionOrdersResponse {
  orders: ExecutionOrder[];
}

export interface ExecutionOrder {
  orderId: string;
  approvalEventId: string;
  candidateIdempotencyKey: string;
  sourceEventId: string;
  portfolioId: string;
  instrumentId: string;
  signalId: string;
  side: SignalSide;
  requestedNotional: string;
  requestedQuantity: string;
  referencePrice: string;
  status: OrderStatus;
  approvedAt: string;
  placedAt: string;
  lastActivityAt: string;
  fills: ExecutionFill[];
}

export interface ExecutionFill {
  fillId: string;
  orderId: string;
  portfolioId: string;
  instrumentId: string;
  sequence: number;
  fillNotional: string;
  fillQuantity: string;
  fillPrice: string;
  cumulativeFilledNotional: string;
  cumulativeFilledQuantity: string;
  orderStatus: OrderStatus;
  filledAt: string;
}

function createBaseListPortfolioExecutionOrdersRequest(): ListPortfolioExecutionOrdersRequest {
  return { portfolioId: "", limit: 0 };
}

export const ListPortfolioExecutionOrdersRequest: MessageFns<ListPortfolioExecutionOrdersRequest> = {
  encode(message: ListPortfolioExecutionOrdersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.portfolioId !== "") {
      writer.uint32(10).string(message.portfolioId);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPortfolioExecutionOrdersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPortfolioExecutionOrdersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListPortfolioExecutionOrdersRequest>, I>>(
    base?: I,
  ): ListPortfolioExecutionOrdersRequest {
    return ListPortfolioExecutionOrdersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPortfolioExecutionOrdersRequest>, I>>(
    object: I,
  ): ListPortfolioExecutionOrdersRequest {
    const message = createBaseListPortfolioExecutionOrdersRequest();
    message.portfolioId = object.portfolioId ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseListPortfolioExecutionOrdersResponse(): ListPortfolioExecutionOrdersResponse {
  return { orders: [] };
}

export const ListPortfolioExecutionOrdersResponse: MessageFns<ListPortfolioExecutionOrdersResponse> = {
  encode(message: ListPortfolioExecutionOrdersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.orders) {
      ExecutionOrder.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPortfolioExecutionOrdersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPortfolioExecutionOrdersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orders.push(ExecutionOrder.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListPortfolioExecutionOrdersResponse>, I>>(
    base?: I,
  ): ListPortfolioExecutionOrdersResponse {
    return ListPortfolioExecutionOrdersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPortfolioExecutionOrdersResponse>, I>>(
    object: I,
  ): ListPortfolioExecutionOrdersResponse {
    const message = createBaseListPortfolioExecutionOrdersResponse();
    message.orders = object.orders?.map((e) => ExecutionOrder.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExecutionOrder(): ExecutionOrder {
  return {
    orderId: "",
    approvalEventId: "",
    candidateIdempotencyKey: "",
    sourceEventId: "",
    portfolioId: "",
    instrumentId: "",
    signalId: "",
    side: 0,
    requestedNotional: "",
    requestedQuantity: "",
    referencePrice: "",
    status: 0,
    approvedAt: "",
    placedAt: "",
    lastActivityAt: "",
    fills: [],
  };
}

export const ExecutionOrder: MessageFns<ExecutionOrder> = {
  encode(message: ExecutionOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.approvalEventId !== "") {
      writer.uint32(18).string(message.approvalEventId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(26).string(message.candidateIdempotencyKey);
    }
    if (message.sourceEventId !== "") {
      writer.uint32(34).string(message.sourceEventId);
    }
    if (message.portfolioId !== "") {
      writer.uint32(42).string(message.portfolioId);
    }
    if (message.instrumentId !== "") {
      writer.uint32(50).string(message.instrumentId);
    }
    if (message.signalId !== "") {
      writer.uint32(58).string(message.signalId);
    }
    if (message.side !== 0) {
      writer.uint32(64).int32(message.side);
    }
    if (message.requestedNotional !== "") {
      writer.uint32(74).string(message.requestedNotional);
    }
    if (message.requestedQuantity !== "") {
      writer.uint32(82).string(message.requestedQuantity);
    }
    if (message.referencePrice !== "") {
      writer.uint32(90).string(message.referencePrice);
    }
    if (message.status !== 0) {
      writer.uint32(96).int32(message.status);
    }
    if (message.approvedAt !== "") {
      writer.uint32(106).string(message.approvedAt);
    }
    if (message.placedAt !== "") {
      writer.uint32(114).string(message.placedAt);
    }
    if (message.lastActivityAt !== "") {
      writer.uint32(122).string(message.lastActivityAt);
    }
    for (const v of message.fills) {
      ExecutionFill.encode(v!, writer.uint32(130).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecutionOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecutionOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.approvalEventId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.signalId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.side = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.requestedNotional = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.requestedQuantity = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.referencePrice = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.approvedAt = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.placedAt = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.lastActivityAt = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.fills.push(ExecutionFill.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ExecutionOrder>, I>>(base?: I): ExecutionOrder {
    return ExecutionOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecutionOrder>, I>>(object: I): ExecutionOrder {
    const message = createBaseExecutionOrder();
    message.orderId = object.orderId ?? "";
    message.approvalEventId = object.approvalEventId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.sourceEventId = object.sourceEventId ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.signalId = object.signalId ?? "";
    message.side = object.side ?? 0;
    message.requestedNotional = object.requestedNotional ?? "";
    message.requestedQuantity = object.requestedQuantity ?? "";
    message.referencePrice = object.referencePrice ?? "";
    message.status = object.status ?? 0;
    message.approvedAt = object.approvedAt ?? "";
    message.placedAt = object.placedAt ?? "";
    message.lastActivityAt = object.lastActivityAt ?? "";
    message.fills = object.fills?.map((e) => ExecutionFill.fromPartial(e)) || [];
    return message;
  },
};

function createBaseExecutionFill(): ExecutionFill {
  return {
    fillId: "",
    orderId: "",
    portfolioId: "",
    instrumentId: "",
    sequence: 0,
    fillNotional: "",
    fillQuantity: "",
    fillPrice: "",
    cumulativeFilledNotional: "",
    cumulativeFilledQuantity: "",
    orderStatus: 0,
    filledAt: "",
  };
}

export const ExecutionFill: MessageFns<ExecutionFill> = {
  encode(message: ExecutionFill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fillId !== "") {
      writer.uint32(10).string(message.fillId);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.portfolioId !== "") {
      writer.uint32(26).string(message.portfolioId);
    }
    if (message.instrumentId !== "") {
      writer.uint32(34).string(message.instrumentId);
    }
    if (message.sequence !== 0) {
      writer.uint32(40).int32(message.sequence);
    }
    if (message.fillNotional !== "") {
      writer.uint32(50).string(message.fillNotional);
    }
    if (message.fillQuantity !== "") {
      writer.uint32(58).string(message.fillQuantity);
    }
    if (message.fillPrice !== "") {
      writer.uint32(66).string(message.fillPrice);
    }
    if (message.cumulativeFilledNotional !== "") {
      writer.uint32(74).string(message.cumulativeFilledNotional);
    }
    if (message.cumulativeFilledQuantity !== "") {
      writer.uint32(82).string(message.cumulativeFilledQuantity);
    }
    if (message.orderStatus !== 0) {
      writer.uint32(88).int32(message.orderStatus);
    }
    if (message.filledAt !== "") {
      writer.uint32(98).string(message.filledAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecutionFill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecutionFill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fillId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sequence = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fillNotional = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fillQuantity = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.fillPrice = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.cumulativeFilledNotional = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.cumulativeFilledQuantity = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.orderStatus = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.filledAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ExecutionFill>, I>>(base?: I): ExecutionFill {
    return ExecutionFill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecutionFill>, I>>(object: I): ExecutionFill {
    const message = createBaseExecutionFill();
    message.fillId = object.fillId ?? "";
    message.orderId = object.orderId ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.sequence = object.sequence ?? 0;
    message.fillNotional = object.fillNotional ?? "";
    message.fillQuantity = object.fillQuantity ?? "";
    message.fillPrice = object.fillPrice ?? "";
    message.cumulativeFilledNotional = object.cumulativeFilledNotional ?? "";
    message.cumulativeFilledQuantity = object.cumulativeFilledQuantity ?? "";
    message.orderStatus = object.orderStatus ?? 0;
    message.filledAt = object.filledAt ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
