// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: services/external_api_facade.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tradingbot.external_api_facade";

export interface StartMarketDataSubscriptionRequest {
  /** Internal instrument identifier (matches Instrument.id). */
  instrumentId: string;
  /** Exchange-native symbol, e.g. "BTCUSDT". */
  symbol: string;
  /** Exchange venue, e.g. "BINANCE". */
  venue: string;
  /**
   * Kline intervals to subscribe to, e.g. ["1m", "5m"].
   * Empty list uses the service default (["1m"]).
   */
  intervals: string[];
}

export interface StartMarketDataSubscriptionResponse {
  /** True if a new subscription was started; false if already active (idempotent). */
  started: boolean;
}

export interface StopMarketDataSubscriptionRequest {
  instrumentId: string;
}

export interface StopMarketDataSubscriptionResponse {
  /** True if a subscription was stopped; false if none was active. */
  stopped: boolean;
}

function createBaseStartMarketDataSubscriptionRequest(): StartMarketDataSubscriptionRequest {
  return { instrumentId: "", symbol: "", venue: "", intervals: [] };
}

export const StartMarketDataSubscriptionRequest: MessageFns<StartMarketDataSubscriptionRequest> = {
  encode(message: StartMarketDataSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrumentId !== "") {
      writer.uint32(10).string(message.instrumentId);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(26).string(message.venue);
    }
    for (const v of message.intervals) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartMarketDataSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartMarketDataSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.intervals.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StartMarketDataSubscriptionRequest>, I>>(
    base?: I,
  ): StartMarketDataSubscriptionRequest {
    return StartMarketDataSubscriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartMarketDataSubscriptionRequest>, I>>(
    object: I,
  ): StartMarketDataSubscriptionRequest {
    const message = createBaseStartMarketDataSubscriptionRequest();
    message.instrumentId = object.instrumentId ?? "";
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.intervals = object.intervals?.map((e) => e) || [];
    return message;
  },
};

function createBaseStartMarketDataSubscriptionResponse(): StartMarketDataSubscriptionResponse {
  return { started: false };
}

export const StartMarketDataSubscriptionResponse: MessageFns<StartMarketDataSubscriptionResponse> = {
  encode(message: StartMarketDataSubscriptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.started !== false) {
      writer.uint32(8).bool(message.started);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartMarketDataSubscriptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartMarketDataSubscriptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.started = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StartMarketDataSubscriptionResponse>, I>>(
    base?: I,
  ): StartMarketDataSubscriptionResponse {
    return StartMarketDataSubscriptionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartMarketDataSubscriptionResponse>, I>>(
    object: I,
  ): StartMarketDataSubscriptionResponse {
    const message = createBaseStartMarketDataSubscriptionResponse();
    message.started = object.started ?? false;
    return message;
  },
};

function createBaseStopMarketDataSubscriptionRequest(): StopMarketDataSubscriptionRequest {
  return { instrumentId: "" };
}

export const StopMarketDataSubscriptionRequest: MessageFns<StopMarketDataSubscriptionRequest> = {
  encode(message: StopMarketDataSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrumentId !== "") {
      writer.uint32(10).string(message.instrumentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StopMarketDataSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopMarketDataSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StopMarketDataSubscriptionRequest>, I>>(
    base?: I,
  ): StopMarketDataSubscriptionRequest {
    return StopMarketDataSubscriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopMarketDataSubscriptionRequest>, I>>(
    object: I,
  ): StopMarketDataSubscriptionRequest {
    const message = createBaseStopMarketDataSubscriptionRequest();
    message.instrumentId = object.instrumentId ?? "";
    return message;
  },
};

function createBaseStopMarketDataSubscriptionResponse(): StopMarketDataSubscriptionResponse {
  return { stopped: false };
}

export const StopMarketDataSubscriptionResponse: MessageFns<StopMarketDataSubscriptionResponse> = {
  encode(message: StopMarketDataSubscriptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stopped !== false) {
      writer.uint32(8).bool(message.stopped);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StopMarketDataSubscriptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStopMarketDataSubscriptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.stopped = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StopMarketDataSubscriptionResponse>, I>>(
    base?: I,
  ): StopMarketDataSubscriptionResponse {
    return StopMarketDataSubscriptionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StopMarketDataSubscriptionResponse>, I>>(
    object: I,
  ): StopMarketDataSubscriptionResponse {
    const message = createBaseStopMarketDataSubscriptionResponse();
    message.stopped = object.stopped ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
