// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: services/portfolio_manager.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AssetClass, Instrument } from "../common/instrument";
import { PortfolioInstrumentConfig, PortfolioSummary, Position } from "../common/portfolio";

export const protobufPackage = "tradingbot.portfolio_manager";

export interface RegisterPortfolioInstrumentRequest {
  portfolioId: string;
  assetClass: AssetClass;
  symbol: string;
  venue: string;
  /** optional */
  externalSymbol: string;
  enabled: boolean;
  targetNotional: string;
  maxTradeNotional: string;
  maxPositionNotional: string;
}

export interface RegisterPortfolioInstrumentResponse {
  configuredInstrument?: PortfolioInstrumentConfig | undefined;
}

export interface ListPortfoliosRequest {
}

export interface ListPortfoliosResponse {
  portfolios: PortfolioSummary[];
}

export interface GetPortfolioRequest {
  portfolioId: string;
}

export interface GetPortfolioResponse {
  summary?: PortfolioSummary | undefined;
  positions: Position[];
  configuredInstruments: PortfolioInstrumentConfig[];
}

export interface ListInstrumentsRequest {
  instrumentIds: string[];
}

export interface ListInstrumentsResponse {
  instruments: Instrument[];
}

function createBaseRegisterPortfolioInstrumentRequest(): RegisterPortfolioInstrumentRequest {
  return {
    portfolioId: "",
    assetClass: 0,
    symbol: "",
    venue: "",
    externalSymbol: "",
    enabled: false,
    targetNotional: "",
    maxTradeNotional: "",
    maxPositionNotional: "",
  };
}

export const RegisterPortfolioInstrumentRequest: MessageFns<RegisterPortfolioInstrumentRequest> = {
  encode(message: RegisterPortfolioInstrumentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.portfolioId !== "") {
      writer.uint32(10).string(message.portfolioId);
    }
    if (message.assetClass !== 0) {
      writer.uint32(16).int32(message.assetClass);
    }
    if (message.symbol !== "") {
      writer.uint32(26).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(34).string(message.venue);
    }
    if (message.externalSymbol !== "") {
      writer.uint32(42).string(message.externalSymbol);
    }
    if (message.enabled !== false) {
      writer.uint32(48).bool(message.enabled);
    }
    if (message.targetNotional !== "") {
      writer.uint32(58).string(message.targetNotional);
    }
    if (message.maxTradeNotional !== "") {
      writer.uint32(66).string(message.maxTradeNotional);
    }
    if (message.maxPositionNotional !== "") {
      writer.uint32(74).string(message.maxPositionNotional);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterPortfolioInstrumentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterPortfolioInstrumentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.assetClass = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.externalSymbol = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.targetNotional = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.maxTradeNotional = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.maxPositionNotional = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegisterPortfolioInstrumentRequest>, I>>(
    base?: I,
  ): RegisterPortfolioInstrumentRequest {
    return RegisterPortfolioInstrumentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterPortfolioInstrumentRequest>, I>>(
    object: I,
  ): RegisterPortfolioInstrumentRequest {
    const message = createBaseRegisterPortfolioInstrumentRequest();
    message.portfolioId = object.portfolioId ?? "";
    message.assetClass = object.assetClass ?? 0;
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.externalSymbol = object.externalSymbol ?? "";
    message.enabled = object.enabled ?? false;
    message.targetNotional = object.targetNotional ?? "";
    message.maxTradeNotional = object.maxTradeNotional ?? "";
    message.maxPositionNotional = object.maxPositionNotional ?? "";
    return message;
  },
};

function createBaseRegisterPortfolioInstrumentResponse(): RegisterPortfolioInstrumentResponse {
  return { configuredInstrument: undefined };
}

export const RegisterPortfolioInstrumentResponse: MessageFns<RegisterPortfolioInstrumentResponse> = {
  encode(message: RegisterPortfolioInstrumentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.configuredInstrument !== undefined) {
      PortfolioInstrumentConfig.encode(message.configuredInstrument, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterPortfolioInstrumentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterPortfolioInstrumentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.configuredInstrument = PortfolioInstrumentConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegisterPortfolioInstrumentResponse>, I>>(
    base?: I,
  ): RegisterPortfolioInstrumentResponse {
    return RegisterPortfolioInstrumentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterPortfolioInstrumentResponse>, I>>(
    object: I,
  ): RegisterPortfolioInstrumentResponse {
    const message = createBaseRegisterPortfolioInstrumentResponse();
    message.configuredInstrument = (object.configuredInstrument !== undefined && object.configuredInstrument !== null)
      ? PortfolioInstrumentConfig.fromPartial(object.configuredInstrument)
      : undefined;
    return message;
  },
};

function createBaseListPortfoliosRequest(): ListPortfoliosRequest {
  return {};
}

export const ListPortfoliosRequest: MessageFns<ListPortfoliosRequest> = {
  encode(_: ListPortfoliosRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPortfoliosRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPortfoliosRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListPortfoliosRequest>, I>>(base?: I): ListPortfoliosRequest {
    return ListPortfoliosRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPortfoliosRequest>, I>>(_: I): ListPortfoliosRequest {
    const message = createBaseListPortfoliosRequest();
    return message;
  },
};

function createBaseListPortfoliosResponse(): ListPortfoliosResponse {
  return { portfolios: [] };
}

export const ListPortfoliosResponse: MessageFns<ListPortfoliosResponse> = {
  encode(message: ListPortfoliosResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.portfolios) {
      PortfolioSummary.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPortfoliosResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPortfoliosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portfolios.push(PortfolioSummary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListPortfoliosResponse>, I>>(base?: I): ListPortfoliosResponse {
    return ListPortfoliosResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPortfoliosResponse>, I>>(object: I): ListPortfoliosResponse {
    const message = createBaseListPortfoliosResponse();
    message.portfolios = object.portfolios?.map((e) => PortfolioSummary.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetPortfolioRequest(): GetPortfolioRequest {
  return { portfolioId: "" };
}

export const GetPortfolioRequest: MessageFns<GetPortfolioRequest> = {
  encode(message: GetPortfolioRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.portfolioId !== "") {
      writer.uint32(10).string(message.portfolioId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPortfolioRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPortfolioRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetPortfolioRequest>, I>>(base?: I): GetPortfolioRequest {
    return GetPortfolioRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPortfolioRequest>, I>>(object: I): GetPortfolioRequest {
    const message = createBaseGetPortfolioRequest();
    message.portfolioId = object.portfolioId ?? "";
    return message;
  },
};

function createBaseGetPortfolioResponse(): GetPortfolioResponse {
  return { summary: undefined, positions: [], configuredInstruments: [] };
}

export const GetPortfolioResponse: MessageFns<GetPortfolioResponse> = {
  encode(message: GetPortfolioResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.summary !== undefined) {
      PortfolioSummary.encode(message.summary, writer.uint32(10).fork()).join();
    }
    for (const v of message.positions) {
      Position.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.configuredInstruments) {
      PortfolioInstrumentConfig.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPortfolioResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPortfolioResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.summary = PortfolioSummary.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.positions.push(Position.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.configuredInstruments.push(PortfolioInstrumentConfig.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetPortfolioResponse>, I>>(base?: I): GetPortfolioResponse {
    return GetPortfolioResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPortfolioResponse>, I>>(object: I): GetPortfolioResponse {
    const message = createBaseGetPortfolioResponse();
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? PortfolioSummary.fromPartial(object.summary)
      : undefined;
    message.positions = object.positions?.map((e) => Position.fromPartial(e)) || [];
    message.configuredInstruments =
      object.configuredInstruments?.map((e) => PortfolioInstrumentConfig.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListInstrumentsRequest(): ListInstrumentsRequest {
  return { instrumentIds: [] };
}

export const ListInstrumentsRequest: MessageFns<ListInstrumentsRequest> = {
  encode(message: ListInstrumentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.instrumentIds) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInstrumentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInstrumentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListInstrumentsRequest>, I>>(base?: I): ListInstrumentsRequest {
    return ListInstrumentsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListInstrumentsRequest>, I>>(object: I): ListInstrumentsRequest {
    const message = createBaseListInstrumentsRequest();
    message.instrumentIds = object.instrumentIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseListInstrumentsResponse(): ListInstrumentsResponse {
  return { instruments: [] };
}

export const ListInstrumentsResponse: MessageFns<ListInstrumentsResponse> = {
  encode(message: ListInstrumentsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.instruments) {
      Instrument.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInstrumentsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInstrumentsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instruments.push(Instrument.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListInstrumentsResponse>, I>>(base?: I): ListInstrumentsResponse {
    return ListInstrumentsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListInstrumentsResponse>, I>>(object: I): ListInstrumentsResponse {
    const message = createBaseListInstrumentsResponse();
    message.instruments = object.instruments?.map((e) => Instrument.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
