// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.1
// source: services/portfolio_manager.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AssetClass, Instrument } from "../common/instrument";
import { PortfolioSummary, Position, Trade } from "../common/portfolio";

export const protobufPackage = "tradingbot.portfolio_manager";

export interface RegisterInstrumentRequest {
  assetClass: AssetClass;
  symbol: string;
  venue: string;
  /** optional */
  externalSymbol: string;
}

export interface RegisterInstrumentResponse {
  /** includes instrument_id */
  instrument?: Instrument | undefined;
}

/** Request for portfolio retrieval */
export interface GetPortfolioRequest {
  /** Account or portfolio id; empty means default account for the caller. */
  accountId: string;
  /** Optional: how many recent trades to include */
  recentTradesLimit: number;
}

/** Response containing portfolio state and recent trades */
export interface GetPortfolioResponse {
  summary?: PortfolioSummary | undefined;
  positions: Position[];
  recentTrades: Trade[];
}

function createBaseRegisterInstrumentRequest(): RegisterInstrumentRequest {
  return { assetClass: 0, symbol: "", venue: "", externalSymbol: "" };
}

export const RegisterInstrumentRequest: MessageFns<RegisterInstrumentRequest> = {
  encode(message: RegisterInstrumentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetClass !== 0) {
      writer.uint32(8).int32(message.assetClass);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(26).string(message.venue);
    }
    if (message.externalSymbol !== "") {
      writer.uint32(34).string(message.externalSymbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterInstrumentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterInstrumentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.assetClass = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.externalSymbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegisterInstrumentRequest>, I>>(base?: I): RegisterInstrumentRequest {
    return RegisterInstrumentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterInstrumentRequest>, I>>(object: I): RegisterInstrumentRequest {
    const message = createBaseRegisterInstrumentRequest();
    message.assetClass = object.assetClass ?? 0;
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.externalSymbol = object.externalSymbol ?? "";
    return message;
  },
};

function createBaseRegisterInstrumentResponse(): RegisterInstrumentResponse {
  return { instrument: undefined };
}

export const RegisterInstrumentResponse: MessageFns<RegisterInstrumentResponse> = {
  encode(message: RegisterInstrumentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrument !== undefined) {
      Instrument.encode(message.instrument, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterInstrumentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterInstrumentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrument = Instrument.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegisterInstrumentResponse>, I>>(base?: I): RegisterInstrumentResponse {
    return RegisterInstrumentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterInstrumentResponse>, I>>(object: I): RegisterInstrumentResponse {
    const message = createBaseRegisterInstrumentResponse();
    message.instrument = (object.instrument !== undefined && object.instrument !== null)
      ? Instrument.fromPartial(object.instrument)
      : undefined;
    return message;
  },
};

function createBaseGetPortfolioRequest(): GetPortfolioRequest {
  return { accountId: "", recentTradesLimit: 0 };
}

export const GetPortfolioRequest: MessageFns<GetPortfolioRequest> = {
  encode(message: GetPortfolioRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accountId !== "") {
      writer.uint32(10).string(message.accountId);
    }
    if (message.recentTradesLimit !== 0) {
      writer.uint32(16).int32(message.recentTradesLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPortfolioRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPortfolioRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.recentTradesLimit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetPortfolioRequest>, I>>(base?: I): GetPortfolioRequest {
    return GetPortfolioRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPortfolioRequest>, I>>(object: I): GetPortfolioRequest {
    const message = createBaseGetPortfolioRequest();
    message.accountId = object.accountId ?? "";
    message.recentTradesLimit = object.recentTradesLimit ?? 0;
    return message;
  },
};

function createBaseGetPortfolioResponse(): GetPortfolioResponse {
  return { summary: undefined, positions: [], recentTrades: [] };
}

export const GetPortfolioResponse: MessageFns<GetPortfolioResponse> = {
  encode(message: GetPortfolioResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.summary !== undefined) {
      PortfolioSummary.encode(message.summary, writer.uint32(10).fork()).join();
    }
    for (const v of message.positions) {
      Position.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.recentTrades) {
      Trade.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPortfolioResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPortfolioResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.summary = PortfolioSummary.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.positions.push(Position.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.recentTrades.push(Trade.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetPortfolioResponse>, I>>(base?: I): GetPortfolioResponse {
    return GetPortfolioResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPortfolioResponse>, I>>(object: I): GetPortfolioResponse {
    const message = createBaseGetPortfolioResponse();
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? PortfolioSummary.fromPartial(object.summary)
      : undefined;
    message.positions = object.positions?.map((e) => Position.fromPartial(e)) || [];
    message.recentTrades = object.recentTrades?.map((e) => Trade.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
