# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/portfolio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/portfolio.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import instrument_pb2 as common_dot_instrument__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x63ommon/portfolio.proto\x12\x11tradingbot.common\x1a\x17\x63ommon/instrument.proto"\xc7\x01\n\x08Position\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\x12\x31\n\ninstrument\x18\x02 \x01(\x0b\x32\x1d.tradingbot.common.Instrument\x12\x10\n\x08quantity\x18\x03 \x01(\t\x12\x1b\n\x13\x61verage_entry_price\x18\x04 \x01(\t\x12\x19\n\x11\x65xposure_notional\x18\x05 \x01(\t\x12\x14\n\x0clast_fill_id\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t"\xbe\x01\n\x10PortfolioSummary\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x1d\n\x15\x65xposure_cap_notional\x18\x04 \x01(\t\x12#\n\x1b\x61ggregate_exposure_notional\x18\x05 \x01(\t\x12\x1b\n\x13open_position_count\x18\x06 \x01(\x05\x12\x12\n\nupdated_at\x18\x07 \x01(\t"\xdd\x01\n\x19PortfolioInstrumentConfig\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\x12\x31\n\ninstrument\x18\x02 \x01(\x0b\x32\x1d.tradingbot.common.Instrument\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12\x17\n\x0ftarget_notional\x18\x04 \x01(\t\x12\x1a\n\x12max_trade_notional\x18\x05 \x01(\t\x12\x1d\n\x15max_position_notional\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.portfolio_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POSITION"]._serialized_start = 71
    _globals["_POSITION"]._serialized_end = 270
    _globals["_PORTFOLIOSUMMARY"]._serialized_start = 273
    _globals["_PORTFOLIOSUMMARY"]._serialized_end = 463
    _globals["_PORTFOLIOINSTRUMENTCONFIG"]._serialized_start = 466
    _globals["_PORTFOLIOINSTRUMENTCONFIG"]._serialized_end = 687
# @@protoc_insertion_point(module_scope)
