# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/signal.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13\x63ommon/signal.proto\x12\x11tradingbot.common"z\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rinstrument_id\x18\x02 \x01(\t\x12+\n\x04side\x18\x03 \x01(\x0e\x32\x1d.tradingbot.common.SignalSide\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03*<\n\nSignalSide\x12\x1b\n\x17SIGNAL_SIDE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.signal_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SIGNALSIDE"]._serialized_start = 166
    _globals["_SIGNALSIDE"]._serialized_end = 226
    _globals["_SIGNAL"]._serialized_start = 42
    _globals["_SIGNAL"]._serialized_end = 164
# @@protoc_insertion_point(module_scope)
