# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/data_ingestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "services/data_ingestion.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dservices/data_ingestion.proto\x12\x19tradingbot.data_ingestion"r\n\x18GetMarketDataBarsRequest\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x0f\n\x07\x66rom_ms\x18\x03 \x01(\x03\x12\r\n\x05to_ms\x18\x04 \x01(\x03\x12\r\n\x05limit\x18\x05 \x01(\x05"Y\n\x19GetMarketDataBarsResponse\x12<\n\x04\x62\x61rs\x18\x01 \x03(\x0b\x32..tradingbot.data_ingestion.MarketDataBarRecord"\xfd\x01\n\x13MarketDataBarRecord\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05venue\x18\x03 \x01(\t\x12\x10\n\x08interval\x18\x04 \x01(\t\x12\x14\n\x0copen_time_ms\x18\x05 \x01(\x03\x12\x15\n\rclose_time_ms\x18\x06 \x01(\x03\x12\x0c\n\x04open\x18\x07 \x01(\t\x12\x0c\n\x04high\x18\x08 \x01(\t\x12\x0b\n\x03low\x18\t \x01(\t\x12\r\n\x05\x63lose\x18\n \x01(\t\x12\x0e\n\x06volume\x18\x0b \x01(\t\x12\x14\n\x0cquote_volume\x18\x0c \x01(\t\x12\x13\n\x0btrade_count\x18\r \x01(\x03\x32\x8f\x01\n\rDataIngestion\x12~\n\x11GetMarketDataBars\x12\x33.tradingbot.data_ingestion.GetMarketDataBarsRequest\x1a\x34.tradingbot.data_ingestion.GetMarketDataBarsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "services.data_ingestion_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETMARKETDATABARSREQUEST"]._serialized_start = 60
    _globals["_GETMARKETDATABARSREQUEST"]._serialized_end = 174
    _globals["_GETMARKETDATABARSRESPONSE"]._serialized_start = 176
    _globals["_GETMARKETDATABARSRESPONSE"]._serialized_end = 265
    _globals["_MARKETDATABARRECORD"]._serialized_start = 268
    _globals["_MARKETDATABARRECORD"]._serialized_end = 521
    _globals["_DATAINGESTION"]._serialized_start = 524
    _globals["_DATAINGESTION"]._serialized_end = 667
# @@protoc_insertion_point(module_scope)
