# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from services import data_ingestion_pb2 as services_dot_data__ingestion__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/data_ingestion_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DataIngestionStub(object):
    """DataIngestion exposes historical market data read queries.
    Used by API Gateway to serve the GET /api/market-data/bars endpoint.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarketDataBars = channel.unary_unary(
            "/tradingbot.data_ingestion.DataIngestion/GetMarketDataBars",
            request_serializer=services_dot_data__ingestion__pb2.GetMarketDataBarsRequest.SerializeToString,
            response_deserializer=services_dot_data__ingestion__pb2.GetMarketDataBarsResponse.FromString,
            _registered_method=True,
        )


class DataIngestionServicer(object):
    """DataIngestion exposes historical market data read queries.
    Used by API Gateway to serve the GET /api/market-data/bars endpoint.
    """

    def GetMarketDataBars(self, request, context):
        """GetMarketDataBars returns stored OHLCV bars for a given instrument,
        interval, and time range. Results are ordered by open_time_ms ascending.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DataIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetMarketDataBars": grpc.unary_unary_rpc_method_handler(
            servicer.GetMarketDataBars,
            request_deserializer=services_dot_data__ingestion__pb2.GetMarketDataBarsRequest.FromString,
            response_serializer=services_dot_data__ingestion__pb2.GetMarketDataBarsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tradingbot.data_ingestion.DataIngestion", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "tradingbot.data_ingestion.DataIngestion", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DataIngestion(object):
    """DataIngestion exposes historical market data read queries.
    Used by API Gateway to serve the GET /api/market-data/bars endpoint.
    """

    @staticmethod
    def GetMarketDataBars(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.data_ingestion.DataIngestion/GetMarketDataBars",
            services_dot_data__ingestion__pb2.GetMarketDataBarsRequest.SerializeToString,
            services_dot_data__ingestion__pb2.GetMarketDataBarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
