# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/external_api_facade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "services/external_api_facade.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"services/external_api_facade.proto\x12\x1etradingbot.external_api_facade"m\n"StartMarketDataSubscriptionRequest\x12\x15\n\rinstrument_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05venue\x18\x03 \x01(\t\x12\x11\n\tintervals\x18\x04 \x03(\t"6\n#StartMarketDataSubscriptionResponse\x12\x0f\n\x07started\x18\x01 \x01(\x08":\n!StopMarketDataSubscriptionRequest\x12\x15\n\rinstrument_id\x18\x01 \x01(\t"5\n"StopMarketDataSubscriptionResponse\x12\x0f\n\x07stopped\x18\x01 \x01(\x08\x32\xe2\x02\n\x11\x45xternalApiFacade\x12\xa6\x01\n\x1bStartMarketDataSubscription\x12\x42.tradingbot.external_api_facade.StartMarketDataSubscriptionRequest\x1a\x43.tradingbot.external_api_facade.StartMarketDataSubscriptionResponse\x12\xa3\x01\n\x1aStopMarketDataSubscription\x12\x41.tradingbot.external_api_facade.StopMarketDataSubscriptionRequest\x1a\x42.tradingbot.external_api_facade.StopMarketDataSubscriptionResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "services.external_api_facade_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STARTMARKETDATASUBSCRIPTIONREQUEST"]._serialized_start = 70
    _globals["_STARTMARKETDATASUBSCRIPTIONREQUEST"]._serialized_end = 179
    _globals["_STARTMARKETDATASUBSCRIPTIONRESPONSE"]._serialized_start = 181
    _globals["_STARTMARKETDATASUBSCRIPTIONRESPONSE"]._serialized_end = 235
    _globals["_STOPMARKETDATASUBSCRIPTIONREQUEST"]._serialized_start = 237
    _globals["_STOPMARKETDATASUBSCRIPTIONREQUEST"]._serialized_end = 295
    _globals["_STOPMARKETDATASUBSCRIPTIONRESPONSE"]._serialized_start = 297
    _globals["_STOPMARKETDATASUBSCRIPTIONRESPONSE"]._serialized_end = 350
    _globals["_EXTERNALAPIFACADE"]._serialized_start = 353
    _globals["_EXTERNALAPIFACADE"]._serialized_end = 707
# @@protoc_insertion_point(module_scope)
