# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from services import external_api_facade_pb2 as services_dot_external__api__facade__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/external_api_facade_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ExternalApiFacadeStub(object):
    """ExternalApiFacade manages connections to external exchange APIs.
    Data Ingestion calls this service to start and stop market data
    subscriptions on behalf of registered instruments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartMarketDataSubscription = channel.unary_unary(
            "/tradingbot.external_api_facade.ExternalApiFacade/StartMarketDataSubscription",
            request_serializer=services_dot_external__api__facade__pb2.StartMarketDataSubscriptionRequest.SerializeToString,
            response_deserializer=services_dot_external__api__facade__pb2.StartMarketDataSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.StopMarketDataSubscription = channel.unary_unary(
            "/tradingbot.external_api_facade.ExternalApiFacade/StopMarketDataSubscription",
            request_serializer=services_dot_external__api__facade__pb2.StopMarketDataSubscriptionRequest.SerializeToString,
            response_deserializer=services_dot_external__api__facade__pb2.StopMarketDataSubscriptionResponse.FromString,
            _registered_method=True,
        )


class ExternalApiFacadeServicer(object):
    """ExternalApiFacade manages connections to external exchange APIs.
    Data Ingestion calls this service to start and stop market data
    subscriptions on behalf of registered instruments.
    """

    def StartMarketDataSubscription(self, request, context):
        """StartMarketDataSubscription starts a Binance kline WebSocket stream
        for the given instrument and intervals. Idempotent: calling it again
        for an already-subscribed instrument is a no-op.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopMarketDataSubscription(self, request, context):
        """StopMarketDataSubscription stops the Binance kline stream for the
        given instrument. No-op if no subscription is active.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExternalApiFacadeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartMarketDataSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.StartMarketDataSubscription,
            request_deserializer=services_dot_external__api__facade__pb2.StartMarketDataSubscriptionRequest.FromString,
            response_serializer=services_dot_external__api__facade__pb2.StartMarketDataSubscriptionResponse.SerializeToString,
        ),
        "StopMarketDataSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.StopMarketDataSubscription,
            request_deserializer=services_dot_external__api__facade__pb2.StopMarketDataSubscriptionRequest.FromString,
            response_serializer=services_dot_external__api__facade__pb2.StopMarketDataSubscriptionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tradingbot.external_api_facade.ExternalApiFacade", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "tradingbot.external_api_facade.ExternalApiFacade", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ExternalApiFacade(object):
    """ExternalApiFacade manages connections to external exchange APIs.
    Data Ingestion calls this service to start and stop market data
    subscriptions on behalf of registered instruments.
    """

    @staticmethod
    def StartMarketDataSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.external_api_facade.ExternalApiFacade/StartMarketDataSubscription",
            services_dot_external__api__facade__pb2.StartMarketDataSubscriptionRequest.SerializeToString,
            services_dot_external__api__facade__pb2.StartMarketDataSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopMarketDataSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.external_api_facade.ExternalApiFacade/StopMarketDataSubscription",
            services_dot_external__api__facade__pb2.StopMarketDataSubscriptionRequest.SerializeToString,
            services_dot_external__api__facade__pb2.StopMarketDataSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
