# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from services import portfolio_manager_pb2 as services_dot_portfolio__manager__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/portfolio_manager_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RiskAndPortfolioManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPortfolioInstrument = channel.unary_unary(
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/RegisterPortfolioInstrument",
            request_serializer=services_dot_portfolio__manager__pb2.RegisterPortfolioInstrumentRequest.SerializeToString,
            response_deserializer=services_dot_portfolio__manager__pb2.RegisterPortfolioInstrumentResponse.FromString,
            _registered_method=True,
        )
        self.ListPortfolios = channel.unary_unary(
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/ListPortfolios",
            request_serializer=services_dot_portfolio__manager__pb2.ListPortfoliosRequest.SerializeToString,
            response_deserializer=services_dot_portfolio__manager__pb2.ListPortfoliosResponse.FromString,
            _registered_method=True,
        )
        self.GetPortfolio = channel.unary_unary(
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/GetPortfolio",
            request_serializer=services_dot_portfolio__manager__pb2.GetPortfolioRequest.SerializeToString,
            response_deserializer=services_dot_portfolio__manager__pb2.GetPortfolioResponse.FromString,
            _registered_method=True,
        )
        self.ListInstruments = channel.unary_unary(
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/ListInstruments",
            request_serializer=services_dot_portfolio__manager__pb2.ListInstrumentsRequest.SerializeToString,
            response_deserializer=services_dot_portfolio__manager__pb2.ListInstrumentsResponse.FromString,
            _registered_method=True,
        )


class RiskAndPortfolioManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPortfolioInstrument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPortfolios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListInstruments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RiskAndPortfolioManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterPortfolioInstrument": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterPortfolioInstrument,
            request_deserializer=services_dot_portfolio__manager__pb2.RegisterPortfolioInstrumentRequest.FromString,
            response_serializer=services_dot_portfolio__manager__pb2.RegisterPortfolioInstrumentResponse.SerializeToString,
        ),
        "ListPortfolios": grpc.unary_unary_rpc_method_handler(
            servicer.ListPortfolios,
            request_deserializer=services_dot_portfolio__manager__pb2.ListPortfoliosRequest.FromString,
            response_serializer=services_dot_portfolio__manager__pb2.ListPortfoliosResponse.SerializeToString,
        ),
        "GetPortfolio": grpc.unary_unary_rpc_method_handler(
            servicer.GetPortfolio,
            request_deserializer=services_dot_portfolio__manager__pb2.GetPortfolioRequest.FromString,
            response_serializer=services_dot_portfolio__manager__pb2.GetPortfolioResponse.SerializeToString,
        ),
        "ListInstruments": grpc.unary_unary_rpc_method_handler(
            servicer.ListInstruments,
            request_deserializer=services_dot_portfolio__manager__pb2.ListInstrumentsRequest.FromString,
            response_serializer=services_dot_portfolio__manager__pb2.ListInstrumentsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tradingbot.portfolio_manager.RiskAndPortfolioManager", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "tradingbot.portfolio_manager.RiskAndPortfolioManager", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RiskAndPortfolioManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPortfolioInstrument(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/RegisterPortfolioInstrument",
            services_dot_portfolio__manager__pb2.RegisterPortfolioInstrumentRequest.SerializeToString,
            services_dot_portfolio__manager__pb2.RegisterPortfolioInstrumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPortfolios(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/ListPortfolios",
            services_dot_portfolio__manager__pb2.ListPortfoliosRequest.SerializeToString,
            services_dot_portfolio__manager__pb2.ListPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPortfolio(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/GetPortfolio",
            services_dot_portfolio__manager__pb2.GetPortfolioRequest.SerializeToString,
            services_dot_portfolio__manager__pb2.GetPortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListInstruments(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tradingbot.portfolio_manager.RiskAndPortfolioManager/ListInstruments",
            services_dot_portfolio__manager__pb2.ListInstrumentsRequest.SerializeToString,
            services_dot_portfolio__manager__pb2.ListInstrumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
