// PostgreSQL (TimescaleDB) implementation of MarketDataRepository.
//
// TypeScript analogy:
//   export class PgMarketDataRepository implements IMarketDataRepository {
//     constructor(private readonly pool: Pool) {}
//     async insertBar(bar: MarketDataBarRow): Promise<void> { ... }
//   }
//
// sqlx differences from a JS Postgres client:
//   - `sqlx::query!()` macro verifies the SQL *at compile time* against a
//     real database or the `.sqlx/` offline cache generated by `cargo sqlx prepare`.
//   - `sqlx::query_as!()` maps result rows directly to a struct — no manual
//     column extraction needed.
//   - The pool (`PgPool`) is `Clone + Send + Sync` — safe to share across threads.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;
use tracing::instrument;

use crate::domain::{BarsQuery, MarketDataBarRow};
use crate::repository::market_data_repository::MarketDataRepository;

pub struct PgMarketDataRepository {
    pool: PgPool,
}

impl PgMarketDataRepository {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

#[async_trait]
impl MarketDataRepository for PgMarketDataRepository {
    // `#[instrument]` automatically creates a tracing span for this call,
    // recording the function name and arguments — like NestJS interceptors
    // that log incoming/outgoing calls.
    #[instrument(skip(self, bar), fields(source_event_id = %bar.source_event_id))]
    async fn insert_bar(&self, bar: &MarketDataBarRow) -> Result<()> {
        // Using the runtime query builder (not the query! macro) so this file
        // compiles without a live database or .sqlx/ cache.
        // The query! macro gives compile-time SQL verification — that can be
        // added later via `cargo sqlx prepare` once the migration has been run.
        //
        // ON CONFLICT DO NOTHING implements idempotency: duplicate source_event_id
        // is silently ignored if the Kafka consumer retries the same message.
        sqlx::query(
            r#"
            INSERT INTO market_data_bars
              (time, instrument_id, symbol, venue, "interval",
               open, high, low, close, volume, quote_volume, trade_count,
               source_event_id)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
            ON CONFLICT (source_event_id) DO NOTHING
            "#,
        )
        .bind(bar.time)
        .bind(&bar.instrument_id)
        .bind(&bar.symbol)
        .bind(&bar.venue)
        .bind(&bar.interval)
        .bind(bar.open)
        .bind(bar.high)
        .bind(bar.low)
        .bind(bar.close)
        .bind(bar.volume)
        .bind(bar.quote_volume)
        .bind(bar.trade_count)
        .bind(&bar.source_event_id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }

    #[instrument(skip(self), fields(
        instrument_id = %query.instrument_id,
        interval = %query.interval,
        limit = query.effective_limit()
    ))]
    async fn get_bars(&self, query: &BarsQuery) -> Result<Vec<MarketDataBarRow>> {
        // sqlx::query_as! maps each row to MarketDataBarRow.
        // The `r#"..."#` syntax is a raw string — no need to escape quotes.
        // Note: using query_as runtime builder — see insert_bar comment above.
        let rows = sqlx::query_as::<_, MarketDataBarRow>(
            r#"
            SELECT
                time,
                instrument_id,
                symbol,
                venue,
                "interval" AS interval,
                open,
                high,
                low,
                close,
                volume,
                quote_volume,
                trade_count,
                source_event_id
            FROM market_data_bars
            WHERE instrument_id = $1
              AND "interval" = $2
              AND time >= $3
              AND time <= $4
            ORDER BY time ASC
            LIMIT $5
            "#,
        )
        .bind(&query.instrument_id)
        .bind(&query.interval)
        .bind(query.from)
        .bind(query.to)
        .bind(query.effective_limit())
        .fetch_all(&self.pool)
        .await?;

        Ok(rows)
    }
}
