# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events/features.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "events/features.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x65vents/features.proto\x12\x11tradingbot.events"4\n\x15IndicatorFeatureValue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"\x9a\x02\n\x16IndicatorFeatureVector\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rinstrument_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\r\n\x05venue\x18\x04 \x01(\t\x12\x10\n\x08interval\x18\x05 \x01(\t\x12\x14\n\x0copen_time_ms\x18\x06 \x01(\x03\x12\x15\n\rclose_time_ms\x18\x07 \x01(\x03\x12\x17\n\x0fsource_event_id\x18\x08 \x01(\t\x12\x13\n\x0b\x66\x65\x61ture_set\x18\t \x01(\t\x12:\n\x08\x66\x65\x61tures\x18\n \x03(\x0b\x32(.tradingbot.events.IndicatorFeatureValue\x12\x15\n\rcalculated_at\x18\x0b \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "events.features_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INDICATORFEATUREVALUE"]._serialized_start = 44
    _globals["_INDICATORFEATUREVALUE"]._serialized_end = 96
    _globals["_INDICATORFEATUREVECTOR"]._serialized_start = 99
    _globals["_INDICATORFEATUREVECTOR"]._serialized_end = 381
# @@protoc_insertion_point(module_scope)
