// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: events/events.proto

/* eslint-disable */
import { Instrument } from "../common/instrument";

export const protobufPackage = "tradingbot.events";

export interface InstrumentRegistered {
  instrument?: Instrument | undefined;
  registeredAt: string;
}
