// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: events/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Instrument } from "../common/instrument";
import { Signal } from "../common/signal";

export const protobufPackage = "tradingbot.events";

export enum TradeDecisionKind {
  TRADE_DECISION_KIND_UNSPECIFIED = 0,
  APPROVED = 1,
  REJECTED = 2,
  UNRECOGNIZED = -1,
}

export enum TradeDecisionReason {
  TRADE_DECISION_REASON_UNSPECIFIED = 0,
  SUBSCRIPTION_DISABLED = 1,
  TRADE_CAP_EXCEEDED = 2,
  INSTRUMENT_EXPOSURE_CAP_EXCEEDED = 3,
  PORTFOLIO_EXPOSURE_CAP_EXCEEDED = 4,
  UNRECOGNIZED = -1,
}

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  PLACED = 1,
  PARTIALLY_FILLED = 2,
  FILLED = 3,
  UNRECOGNIZED = -1,
}

export interface InstrumentRegistered {
  instrument?: Instrument | undefined;
  registeredAt: string;
}

export interface PortfolioSignalCandidate {
  signal?: Signal | undefined;
  sourceEventId: string;
  portfolioId: string;
  candidateIdempotencyKey: string;
  signalReceivedAt: string;
}

export interface TradeDecision {
  signal?: Signal | undefined;
  sourceEventId: string;
  portfolioId: string;
  candidateIdempotencyKey: string;
  decision: TradeDecisionKind;
  reasonCodes: TradeDecisionReason[];
  requestedNotional: string;
  requestedQuantity: string;
  referencePrice: string;
  decidedAt: string;
}

export interface OrderPlaced {
  orderId: string;
  approvalEventId: string;
  sourceEventId: string;
  candidateIdempotencyKey: string;
  portfolioId: string;
  signal?: Signal | undefined;
  requestedNotional: string;
  requestedQuantity: string;
  referencePrice: string;
  status: OrderStatus;
  placedAt: string;
}

export interface OrderFill {
  fillId: string;
  orderId: string;
  approvalEventId: string;
  sourceEventId: string;
  candidateIdempotencyKey: string;
  portfolioId: string;
  signal?: Signal | undefined;
  sequence: number;
  fillNotional: string;
  fillQuantity: string;
  fillPrice: string;
  cumulativeFilledNotional: string;
  cumulativeFilledQuantity: string;
  orderStatus: OrderStatus;
  filledAt: string;
}

export interface PortfolioUpdated {
  portfolioId: string;
  sourceFillId: string;
  orderId: string;
  instrumentId: string;
  aggregateExposureNotional: string;
  openPositionCount: number;
  changedPositionQuantity: string;
  changedPositionAverageEntryPrice: string;
  changedPositionExposureNotional: string;
  updatedAt: string;
}

function createBaseInstrumentRegistered(): InstrumentRegistered {
  return { instrument: undefined, registeredAt: "" };
}

export const InstrumentRegistered: MessageFns<InstrumentRegistered> = {
  encode(message: InstrumentRegistered, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrument !== undefined) {
      Instrument.encode(message.instrument, writer.uint32(10).fork()).join();
    }
    if (message.registeredAt !== "") {
      writer.uint32(18).string(message.registeredAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstrumentRegistered {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstrumentRegistered();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrument = Instrument.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.registeredAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<InstrumentRegistered>, I>>(base?: I): InstrumentRegistered {
    return InstrumentRegistered.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstrumentRegistered>, I>>(object: I): InstrumentRegistered {
    const message = createBaseInstrumentRegistered();
    message.instrument = (object.instrument !== undefined && object.instrument !== null)
      ? Instrument.fromPartial(object.instrument)
      : undefined;
    message.registeredAt = object.registeredAt ?? "";
    return message;
  },
};

function createBasePortfolioSignalCandidate(): PortfolioSignalCandidate {
  return { signal: undefined, sourceEventId: "", portfolioId: "", candidateIdempotencyKey: "", signalReceivedAt: "" };
}

export const PortfolioSignalCandidate: MessageFns<PortfolioSignalCandidate> = {
  encode(message: PortfolioSignalCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(10).fork()).join();
    }
    if (message.sourceEventId !== "") {
      writer.uint32(18).string(message.sourceEventId);
    }
    if (message.portfolioId !== "") {
      writer.uint32(26).string(message.portfolioId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(34).string(message.candidateIdempotencyKey);
    }
    if (message.signalReceivedAt !== "") {
      writer.uint32(42).string(message.signalReceivedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PortfolioSignalCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePortfolioSignalCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.signalReceivedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PortfolioSignalCandidate>, I>>(base?: I): PortfolioSignalCandidate {
    return PortfolioSignalCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortfolioSignalCandidate>, I>>(object: I): PortfolioSignalCandidate {
    const message = createBasePortfolioSignalCandidate();
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.sourceEventId = object.sourceEventId ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.signalReceivedAt = object.signalReceivedAt ?? "";
    return message;
  },
};

function createBaseTradeDecision(): TradeDecision {
  return {
    signal: undefined,
    sourceEventId: "",
    portfolioId: "",
    candidateIdempotencyKey: "",
    decision: 0,
    reasonCodes: [],
    requestedNotional: "",
    requestedQuantity: "",
    referencePrice: "",
    decidedAt: "",
  };
}

export const TradeDecision: MessageFns<TradeDecision> = {
  encode(message: TradeDecision, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(10).fork()).join();
    }
    if (message.sourceEventId !== "") {
      writer.uint32(18).string(message.sourceEventId);
    }
    if (message.portfolioId !== "") {
      writer.uint32(26).string(message.portfolioId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(34).string(message.candidateIdempotencyKey);
    }
    if (message.decision !== 0) {
      writer.uint32(40).int32(message.decision);
    }
    writer.uint32(50).fork();
    for (const v of message.reasonCodes) {
      writer.int32(v);
    }
    writer.join();
    if (message.requestedNotional !== "") {
      writer.uint32(58).string(message.requestedNotional);
    }
    if (message.requestedQuantity !== "") {
      writer.uint32(66).string(message.requestedQuantity);
    }
    if (message.referencePrice !== "") {
      writer.uint32(74).string(message.referencePrice);
    }
    if (message.decidedAt !== "") {
      writer.uint32(82).string(message.decidedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TradeDecision {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTradeDecision();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.decision = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.reasonCodes.push(reader.int32() as any);

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.reasonCodes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestedNotional = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.requestedQuantity = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.referencePrice = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.decidedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TradeDecision>, I>>(base?: I): TradeDecision {
    return TradeDecision.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TradeDecision>, I>>(object: I): TradeDecision {
    const message = createBaseTradeDecision();
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.sourceEventId = object.sourceEventId ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.decision = object.decision ?? 0;
    message.reasonCodes = object.reasonCodes?.map((e) => e) || [];
    message.requestedNotional = object.requestedNotional ?? "";
    message.requestedQuantity = object.requestedQuantity ?? "";
    message.referencePrice = object.referencePrice ?? "";
    message.decidedAt = object.decidedAt ?? "";
    return message;
  },
};

function createBaseOrderPlaced(): OrderPlaced {
  return {
    orderId: "",
    approvalEventId: "",
    sourceEventId: "",
    candidateIdempotencyKey: "",
    portfolioId: "",
    signal: undefined,
    requestedNotional: "",
    requestedQuantity: "",
    referencePrice: "",
    status: 0,
    placedAt: "",
  };
}

export const OrderPlaced: MessageFns<OrderPlaced> = {
  encode(message: OrderPlaced, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.approvalEventId !== "") {
      writer.uint32(18).string(message.approvalEventId);
    }
    if (message.sourceEventId !== "") {
      writer.uint32(26).string(message.sourceEventId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(34).string(message.candidateIdempotencyKey);
    }
    if (message.portfolioId !== "") {
      writer.uint32(42).string(message.portfolioId);
    }
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(50).fork()).join();
    }
    if (message.requestedNotional !== "") {
      writer.uint32(58).string(message.requestedNotional);
    }
    if (message.requestedQuantity !== "") {
      writer.uint32(66).string(message.requestedQuantity);
    }
    if (message.referencePrice !== "") {
      writer.uint32(74).string(message.referencePrice);
    }
    if (message.status !== 0) {
      writer.uint32(80).int32(message.status);
    }
    if (message.placedAt !== "") {
      writer.uint32(90).string(message.placedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderPlaced {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderPlaced();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.approvalEventId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestedNotional = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.requestedQuantity = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.referencePrice = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.placedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OrderPlaced>, I>>(base?: I): OrderPlaced {
    return OrderPlaced.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderPlaced>, I>>(object: I): OrderPlaced {
    const message = createBaseOrderPlaced();
    message.orderId = object.orderId ?? "";
    message.approvalEventId = object.approvalEventId ?? "";
    message.sourceEventId = object.sourceEventId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.requestedNotional = object.requestedNotional ?? "";
    message.requestedQuantity = object.requestedQuantity ?? "";
    message.referencePrice = object.referencePrice ?? "";
    message.status = object.status ?? 0;
    message.placedAt = object.placedAt ?? "";
    return message;
  },
};

function createBaseOrderFill(): OrderFill {
  return {
    fillId: "",
    orderId: "",
    approvalEventId: "",
    sourceEventId: "",
    candidateIdempotencyKey: "",
    portfolioId: "",
    signal: undefined,
    sequence: 0,
    fillNotional: "",
    fillQuantity: "",
    fillPrice: "",
    cumulativeFilledNotional: "",
    cumulativeFilledQuantity: "",
    orderStatus: 0,
    filledAt: "",
  };
}

export const OrderFill: MessageFns<OrderFill> = {
  encode(message: OrderFill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fillId !== "") {
      writer.uint32(10).string(message.fillId);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    if (message.approvalEventId !== "") {
      writer.uint32(26).string(message.approvalEventId);
    }
    if (message.sourceEventId !== "") {
      writer.uint32(34).string(message.sourceEventId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(42).string(message.candidateIdempotencyKey);
    }
    if (message.portfolioId !== "") {
      writer.uint32(50).string(message.portfolioId);
    }
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(58).fork()).join();
    }
    if (message.sequence !== 0) {
      writer.uint32(64).int32(message.sequence);
    }
    if (message.fillNotional !== "") {
      writer.uint32(74).string(message.fillNotional);
    }
    if (message.fillQuantity !== "") {
      writer.uint32(82).string(message.fillQuantity);
    }
    if (message.fillPrice !== "") {
      writer.uint32(90).string(message.fillPrice);
    }
    if (message.cumulativeFilledNotional !== "") {
      writer.uint32(98).string(message.cumulativeFilledNotional);
    }
    if (message.cumulativeFilledQuantity !== "") {
      writer.uint32(106).string(message.cumulativeFilledQuantity);
    }
    if (message.orderStatus !== 0) {
      writer.uint32(112).int32(message.orderStatus);
    }
    if (message.filledAt !== "") {
      writer.uint32(122).string(message.filledAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderFill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderFill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fillId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.approvalEventId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.sequence = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.fillNotional = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.fillQuantity = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.fillPrice = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.cumulativeFilledNotional = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.cumulativeFilledQuantity = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.orderStatus = reader.int32() as any;
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.filledAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OrderFill>, I>>(base?: I): OrderFill {
    return OrderFill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderFill>, I>>(object: I): OrderFill {
    const message = createBaseOrderFill();
    message.fillId = object.fillId ?? "";
    message.orderId = object.orderId ?? "";
    message.approvalEventId = object.approvalEventId ?? "";
    message.sourceEventId = object.sourceEventId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.sequence = object.sequence ?? 0;
    message.fillNotional = object.fillNotional ?? "";
    message.fillQuantity = object.fillQuantity ?? "";
    message.fillPrice = object.fillPrice ?? "";
    message.cumulativeFilledNotional = object.cumulativeFilledNotional ?? "";
    message.cumulativeFilledQuantity = object.cumulativeFilledQuantity ?? "";
    message.orderStatus = object.orderStatus ?? 0;
    message.filledAt = object.filledAt ?? "";
    return message;
  },
};

function createBasePortfolioUpdated(): PortfolioUpdated {
  return {
    portfolioId: "",
    sourceFillId: "",
    orderId: "",
    instrumentId: "",
    aggregateExposureNotional: "",
    openPositionCount: 0,
    changedPositionQuantity: "",
    changedPositionAverageEntryPrice: "",
    changedPositionExposureNotional: "",
    updatedAt: "",
  };
}

export const PortfolioUpdated: MessageFns<PortfolioUpdated> = {
  encode(message: PortfolioUpdated, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.portfolioId !== "") {
      writer.uint32(10).string(message.portfolioId);
    }
    if (message.sourceFillId !== "") {
      writer.uint32(18).string(message.sourceFillId);
    }
    if (message.orderId !== "") {
      writer.uint32(26).string(message.orderId);
    }
    if (message.instrumentId !== "") {
      writer.uint32(34).string(message.instrumentId);
    }
    if (message.aggregateExposureNotional !== "") {
      writer.uint32(42).string(message.aggregateExposureNotional);
    }
    if (message.openPositionCount !== 0) {
      writer.uint32(48).int32(message.openPositionCount);
    }
    if (message.changedPositionQuantity !== "") {
      writer.uint32(58).string(message.changedPositionQuantity);
    }
    if (message.changedPositionAverageEntryPrice !== "") {
      writer.uint32(66).string(message.changedPositionAverageEntryPrice);
    }
    if (message.changedPositionExposureNotional !== "") {
      writer.uint32(74).string(message.changedPositionExposureNotional);
    }
    if (message.updatedAt !== "") {
      writer.uint32(82).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PortfolioUpdated {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePortfolioUpdated();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceFillId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.aggregateExposureNotional = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.openPositionCount = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.changedPositionQuantity = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.changedPositionAverageEntryPrice = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.changedPositionExposureNotional = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PortfolioUpdated>, I>>(base?: I): PortfolioUpdated {
    return PortfolioUpdated.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortfolioUpdated>, I>>(object: I): PortfolioUpdated {
    const message = createBasePortfolioUpdated();
    message.portfolioId = object.portfolioId ?? "";
    message.sourceFillId = object.sourceFillId ?? "";
    message.orderId = object.orderId ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.aggregateExposureNotional = object.aggregateExposureNotional ?? "";
    message.openPositionCount = object.openPositionCount ?? 0;
    message.changedPositionQuantity = object.changedPositionQuantity ?? "";
    message.changedPositionAverageEntryPrice = object.changedPositionAverageEntryPrice ?? "";
    message.changedPositionExposureNotional = object.changedPositionExposureNotional ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
