// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v7.34.1
// source: events/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Instrument } from "../common/instrument";
import { Signal } from "../common/signal";

export const protobufPackage = "tradingbot.events";

export enum TradeDecisionKind {
  TRADE_DECISION_KIND_UNSPECIFIED = 0,
  APPROVED = 1,
  REJECTED = 2,
  UNRECOGNIZED = -1,
}

export enum TradeDecisionReason {
  TRADE_DECISION_REASON_UNSPECIFIED = 0,
  SUBSCRIPTION_DISABLED = 1,
  TRADE_CAP_EXCEEDED = 2,
  INSTRUMENT_EXPOSURE_CAP_EXCEEDED = 3,
  PORTFOLIO_EXPOSURE_CAP_EXCEEDED = 4,
  UNRECOGNIZED = -1,
}

export interface InstrumentRegistered {
  instrument?: Instrument | undefined;
  registeredAt: string;
}

export interface PortfolioSignalCandidate {
  signal?: Signal | undefined;
  sourceEventId: string;
  portfolioId: string;
  candidateIdempotencyKey: string;
  signalReceivedAt: string;
}

export interface TradeDecision {
  signal?: Signal | undefined;
  sourceEventId: string;
  portfolioId: string;
  candidateIdempotencyKey: string;
  decision: TradeDecisionKind;
  reasonCodes: TradeDecisionReason[];
  requestedNotional: string;
  requestedQuantity: string;
  referencePrice: string;
  decidedAt: string;
}

function createBaseInstrumentRegistered(): InstrumentRegistered {
  return { instrument: undefined, registeredAt: "" };
}

export const InstrumentRegistered: MessageFns<InstrumentRegistered> = {
  encode(message: InstrumentRegistered, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrument !== undefined) {
      Instrument.encode(message.instrument, writer.uint32(10).fork()).join();
    }
    if (message.registeredAt !== "") {
      writer.uint32(18).string(message.registeredAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstrumentRegistered {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstrumentRegistered();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrument = Instrument.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.registeredAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<InstrumentRegistered>, I>>(base?: I): InstrumentRegistered {
    return InstrumentRegistered.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstrumentRegistered>, I>>(object: I): InstrumentRegistered {
    const message = createBaseInstrumentRegistered();
    message.instrument = (object.instrument !== undefined && object.instrument !== null)
      ? Instrument.fromPartial(object.instrument)
      : undefined;
    message.registeredAt = object.registeredAt ?? "";
    return message;
  },
};

function createBasePortfolioSignalCandidate(): PortfolioSignalCandidate {
  return { signal: undefined, sourceEventId: "", portfolioId: "", candidateIdempotencyKey: "", signalReceivedAt: "" };
}

export const PortfolioSignalCandidate: MessageFns<PortfolioSignalCandidate> = {
  encode(message: PortfolioSignalCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(10).fork()).join();
    }
    if (message.sourceEventId !== "") {
      writer.uint32(18).string(message.sourceEventId);
    }
    if (message.portfolioId !== "") {
      writer.uint32(26).string(message.portfolioId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(34).string(message.candidateIdempotencyKey);
    }
    if (message.signalReceivedAt !== "") {
      writer.uint32(42).string(message.signalReceivedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PortfolioSignalCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePortfolioSignalCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.signalReceivedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PortfolioSignalCandidate>, I>>(base?: I): PortfolioSignalCandidate {
    return PortfolioSignalCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortfolioSignalCandidate>, I>>(object: I): PortfolioSignalCandidate {
    const message = createBasePortfolioSignalCandidate();
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.sourceEventId = object.sourceEventId ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.signalReceivedAt = object.signalReceivedAt ?? "";
    return message;
  },
};

function createBaseTradeDecision(): TradeDecision {
  return {
    signal: undefined,
    sourceEventId: "",
    portfolioId: "",
    candidateIdempotencyKey: "",
    decision: 0,
    reasonCodes: [],
    requestedNotional: "",
    requestedQuantity: "",
    referencePrice: "",
    decidedAt: "",
  };
}

export const TradeDecision: MessageFns<TradeDecision> = {
  encode(message: TradeDecision, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== undefined) {
      Signal.encode(message.signal, writer.uint32(10).fork()).join();
    }
    if (message.sourceEventId !== "") {
      writer.uint32(18).string(message.sourceEventId);
    }
    if (message.portfolioId !== "") {
      writer.uint32(26).string(message.portfolioId);
    }
    if (message.candidateIdempotencyKey !== "") {
      writer.uint32(34).string(message.candidateIdempotencyKey);
    }
    if (message.decision !== 0) {
      writer.uint32(40).int32(message.decision);
    }
    writer.uint32(50).fork();
    for (const v of message.reasonCodes) {
      writer.int32(v);
    }
    writer.join();
    if (message.requestedNotional !== "") {
      writer.uint32(58).string(message.requestedNotional);
    }
    if (message.requestedQuantity !== "") {
      writer.uint32(66).string(message.requestedQuantity);
    }
    if (message.referencePrice !== "") {
      writer.uint32(74).string(message.referencePrice);
    }
    if (message.decidedAt !== "") {
      writer.uint32(82).string(message.decidedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TradeDecision {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTradeDecision();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = Signal.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.portfolioId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidateIdempotencyKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.decision = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.reasonCodes.push(reader.int32() as any);

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.reasonCodes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestedNotional = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.requestedQuantity = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.referencePrice = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.decidedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TradeDecision>, I>>(base?: I): TradeDecision {
    return TradeDecision.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TradeDecision>, I>>(object: I): TradeDecision {
    const message = createBaseTradeDecision();
    message.signal = (object.signal !== undefined && object.signal !== null)
      ? Signal.fromPartial(object.signal)
      : undefined;
    message.sourceEventId = object.sourceEventId ?? "";
    message.portfolioId = object.portfolioId ?? "";
    message.candidateIdempotencyKey = object.candidateIdempotencyKey ?? "";
    message.decision = object.decision ?? 0;
    message.reasonCodes = object.reasonCodes?.map((e) => e) || [];
    message.requestedNotional = object.requestedNotional ?? "";
    message.requestedQuantity = object.requestedQuantity ?? "";
    message.referencePrice = object.referencePrice ?? "";
    message.decidedAt = object.decidedAt ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
