// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: events/features.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tradingbot.events";

/**
 * IndicatorFeatureValue is one named numeric feature emitted by Feature
 * Engineering. Values are decimal strings so Rust, TypeScript, and future
 * Python consumers do not lose precision through binary floating point.
 */
export interface IndicatorFeatureValue {
  /** Stable feature name, e.g. "rsi.close.14". */
  name: string;
  /** Numeric value represented as a string. */
  value: string;
}

/**
 * IndicatorFeatureVector is published to `features.indicators` once the core
 * indicator set is ready for a finalized market data bar.
 */
export interface IndicatorFeatureVector {
  /** Deterministic event/business identity for the feature vector. */
  id: string;
  /** Internal instrument identifier. */
  instrumentId: string;
  /** Exchange-native symbol, e.g. "BTCUSDT". */
  symbol: string;
  /** Exchange venue, e.g. "BINANCE". */
  venue: string;
  /** Kline interval, e.g. "1m", "5m", "1h". */
  interval: string;
  /** Source bar open time as Unix epoch milliseconds. */
  openTimeMs: number;
  /** Source bar close time as Unix epoch milliseconds. */
  closeTimeMs: number;
  /** Kafka event-id of the source market.raw.data event. */
  sourceEventId: string;
  /** Feature-set version, e.g. "core-v1". */
  featureSet: string;
  /** Computed indicator values. */
  features: IndicatorFeatureValue[];
  /** ISO-8601 timestamp for when this vector was calculated. */
  calculatedAt: string;
}

function createBaseIndicatorFeatureValue(): IndicatorFeatureValue {
  return { name: "", value: "" };
}

export const IndicatorFeatureValue: MessageFns<IndicatorFeatureValue> = {
  encode(message: IndicatorFeatureValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndicatorFeatureValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndicatorFeatureValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<IndicatorFeatureValue>, I>>(base?: I): IndicatorFeatureValue {
    return IndicatorFeatureValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IndicatorFeatureValue>, I>>(object: I): IndicatorFeatureValue {
    const message = createBaseIndicatorFeatureValue();
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseIndicatorFeatureVector(): IndicatorFeatureVector {
  return {
    id: "",
    instrumentId: "",
    symbol: "",
    venue: "",
    interval: "",
    openTimeMs: 0,
    closeTimeMs: 0,
    sourceEventId: "",
    featureSet: "",
    features: [],
    calculatedAt: "",
  };
}

export const IndicatorFeatureVector: MessageFns<IndicatorFeatureVector> = {
  encode(message: IndicatorFeatureVector, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.instrumentId !== "") {
      writer.uint32(18).string(message.instrumentId);
    }
    if (message.symbol !== "") {
      writer.uint32(26).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(34).string(message.venue);
    }
    if (message.interval !== "") {
      writer.uint32(42).string(message.interval);
    }
    if (message.openTimeMs !== 0) {
      writer.uint32(48).int64(message.openTimeMs);
    }
    if (message.closeTimeMs !== 0) {
      writer.uint32(56).int64(message.closeTimeMs);
    }
    if (message.sourceEventId !== "") {
      writer.uint32(66).string(message.sourceEventId);
    }
    if (message.featureSet !== "") {
      writer.uint32(74).string(message.featureSet);
    }
    for (const v of message.features) {
      IndicatorFeatureValue.encode(v!, writer.uint32(82).fork()).join();
    }
    if (message.calculatedAt !== "") {
      writer.uint32(90).string(message.calculatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndicatorFeatureVector {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndicatorFeatureVector();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.interval = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.openTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.closeTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.sourceEventId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.featureSet = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.features.push(IndicatorFeatureValue.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.calculatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<IndicatorFeatureVector>, I>>(base?: I): IndicatorFeatureVector {
    return IndicatorFeatureVector.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IndicatorFeatureVector>, I>>(object: I): IndicatorFeatureVector {
    const message = createBaseIndicatorFeatureVector();
    message.id = object.id ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.interval = object.interval ?? "";
    message.openTimeMs = object.openTimeMs ?? 0;
    message.closeTimeMs = object.closeTimeMs ?? 0;
    message.sourceEventId = object.sourceEventId ?? "";
    message.featureSet = object.featureSet ?? "";
    message.features = object.features?.map((e) => IndicatorFeatureValue.fromPartial(e)) || [];
    message.calculatedAt = object.calculatedAt ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
