// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: events/market.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tradingbot.events";

/**
 * MarketDataBar represents a single OHLCV candlestick bar received from
 * an exchange. Published to the `market.raw.data` Kafka topic by the
 * External API Facade and consumed by Data Ingestion.
 */
export interface MarketDataBar {
  /** Internal instrument identifier (UUID, matches Instrument.id). */
  instrumentId: string;
  /** Exchange-native symbol, e.g. "BTCUSDT". */
  symbol: string;
  /** Exchange venue, e.g. "BINANCE". */
  venue: string;
  /** Kline interval, e.g. "1m", "5m", "1h". */
  interval: string;
  /** Open time of the bar as Unix epoch milliseconds. */
  openTimeMs: number;
  /** Close time of the bar as Unix epoch milliseconds. */
  closeTimeMs: number;
  /** OHLCV values as decimal strings to avoid floating-point precision loss. */
  open: string;
  high: string;
  low: string;
  close: string;
  volume: string;
  /** Quote asset volume (e.g. USDT volume). */
  quoteVolume: string;
  /** Number of trades in the bar. */
  tradeCount: number;
  /**
   * True when this is the final (closed) bar for the interval.
   * False for in-progress bars streamed before close.
   */
  isFinal: boolean;
}

function createBaseMarketDataBar(): MarketDataBar {
  return {
    instrumentId: "",
    symbol: "",
    venue: "",
    interval: "",
    openTimeMs: 0,
    closeTimeMs: 0,
    open: "",
    high: "",
    low: "",
    close: "",
    volume: "",
    quoteVolume: "",
    tradeCount: 0,
    isFinal: false,
  };
}

export const MarketDataBar: MessageFns<MarketDataBar> = {
  encode(message: MarketDataBar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrumentId !== "") {
      writer.uint32(10).string(message.instrumentId);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(26).string(message.venue);
    }
    if (message.interval !== "") {
      writer.uint32(34).string(message.interval);
    }
    if (message.openTimeMs !== 0) {
      writer.uint32(40).int64(message.openTimeMs);
    }
    if (message.closeTimeMs !== 0) {
      writer.uint32(48).int64(message.closeTimeMs);
    }
    if (message.open !== "") {
      writer.uint32(58).string(message.open);
    }
    if (message.high !== "") {
      writer.uint32(66).string(message.high);
    }
    if (message.low !== "") {
      writer.uint32(74).string(message.low);
    }
    if (message.close !== "") {
      writer.uint32(82).string(message.close);
    }
    if (message.volume !== "") {
      writer.uint32(90).string(message.volume);
    }
    if (message.quoteVolume !== "") {
      writer.uint32(98).string(message.quoteVolume);
    }
    if (message.tradeCount !== 0) {
      writer.uint32(104).int64(message.tradeCount);
    }
    if (message.isFinal !== false) {
      writer.uint32(112).bool(message.isFinal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketDataBar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketDataBar();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.interval = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.openTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.closeTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.open = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.high = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.low = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.close = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.volume = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.quoteVolume = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.tradeCount = longToNumber(reader.int64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MarketDataBar>, I>>(base?: I): MarketDataBar {
    return MarketDataBar.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketDataBar>, I>>(object: I): MarketDataBar {
    const message = createBaseMarketDataBar();
    message.instrumentId = object.instrumentId ?? "";
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.interval = object.interval ?? "";
    message.openTimeMs = object.openTimeMs ?? 0;
    message.closeTimeMs = object.closeTimeMs ?? 0;
    message.open = object.open ?? "";
    message.high = object.high ?? "";
    message.low = object.low ?? "";
    message.close = object.close ?? "";
    message.volume = object.volume ?? "";
    message.quoteVolume = object.quoteVolume ?? "";
    message.tradeCount = object.tradeCount ?? 0;
    message.isFinal = object.isFinal ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
