// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: common/signal.proto

/* eslint-disable */

export const protobufPackage = "tradingbot.common";

/** Strongly typed side field. */
export enum SignalSide {
  SIGNAL_SIDE_UNSPECIFIED = 0,
  BUY = 1,
  SELL = 2,
  UNRECOGNIZED = -1,
}

/** Signal represents a single trading signal. */
export interface Signal {
  /** unique identifier for the signal */
  id: string;
  /** market symbol, e.g. "UUID" */
  instrumentId: string;
  /** Use an enum for the side to avoid clients passing arbitrary strings. */
  side: SignalSide;
  /** suggested price */
  price: number;
  /** unix epoch milliseconds (int64) — choose UTC timestamps consistently. */
  timestamp: number;
}
