// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.1
// source: common/instrument.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tradingbot.common";

export enum AssetClass {
  ASSET_CLASS_UNSPECIFIED = 0,
  CRYPTO = 1,
  STOCK = 2,
  UNRECOGNIZED = -1,
}

export interface Instrument {
  /** Internal unique ID (UUID or generated by Risk Manager) */
  id: string;
  /** CRYPTO, STOCK, etc. */
  assetClass: AssetClass;
  /** e.g. "BTC/USDT", "GOGL" */
  symbol: string;
  /** e.g. "BINANCE", "NASDAQ", "NYSE", "COINBASE" */
  venue: string;
  /** Exchange-specific ticker, e.g. "BTCUSDT" or "GOGL" */
  externalSymbol?: string | undefined;
}

function createBaseInstrument(): Instrument {
  return { id: "", assetClass: 0, symbol: "", venue: "", externalSymbol: undefined };
}

export const Instrument: MessageFns<Instrument> = {
  encode(message: Instrument, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.assetClass !== 0) {
      writer.uint32(16).int32(message.assetClass);
    }
    if (message.symbol !== "") {
      writer.uint32(26).string(message.symbol);
    }
    if (message.venue !== "") {
      writer.uint32(34).string(message.venue);
    }
    if (message.externalSymbol !== undefined) {
      writer.uint32(42).string(message.externalSymbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Instrument {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstrument();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.assetClass = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.venue = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.externalSymbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Instrument>, I>>(base?: I): Instrument {
    return Instrument.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Instrument>, I>>(object: I): Instrument {
    const message = createBaseInstrument();
    message.id = object.id ?? "";
    message.assetClass = object.assetClass ?? 0;
    message.symbol = object.symbol ?? "";
    message.venue = object.venue ?? "";
    message.externalSymbol = object.externalSymbol ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
