// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.1
// source: common/portfolio.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SignalSide } from "./signal";

export const protobufPackage = "tradingbot.common";

/** Trade represents an executed trade or fill. */
export interface Trade {
  /** trade id */
  id: string;
  /** e.g. "UUID" */
  instrumentId: string;
  side: SignalSide;
  price: number;
  quantity: number;
  /** unix epoch milliseconds */
  timestamp: number;
}

/** Position represents an open position in the portfolio. */
export interface Position {
  /** e.g. "UUID" */
  instrumentId: string;
  /** positive for net long, negative for net short */
  quantity: number;
  /** average entry price */
  avgPrice: number;
  unrealizedPnl: number;
}

/** Portfolio summary contains overall account metrics. */
export interface PortfolioSummary {
  totalBalance: number;
  availableBalance: number;
  pnl: number;
}

function createBaseTrade(): Trade {
  return { id: "", instrumentId: "", side: 0, price: 0, quantity: 0, timestamp: 0 };
}

export const Trade: MessageFns<Trade> = {
  encode(message: Trade, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.instrumentId !== "") {
      writer.uint32(18).string(message.instrumentId);
    }
    if (message.side !== 0) {
      writer.uint32(24).int32(message.side);
    }
    if (message.price !== 0) {
      writer.uint32(33).double(message.price);
    }
    if (message.quantity !== 0) {
      writer.uint32(41).double(message.quantity);
    }
    if (message.timestamp !== 0) {
      writer.uint32(48).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trade {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrade();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.side = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Trade>, I>>(base?: I): Trade {
    return Trade.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trade>, I>>(object: I): Trade {
    const message = createBaseTrade();
    message.id = object.id ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.side = object.side ?? 0;
    message.price = object.price ?? 0;
    message.quantity = object.quantity ?? 0;
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBasePosition(): Position {
  return { instrumentId: "", quantity: 0, avgPrice: 0, unrealizedPnl: 0 };
}

export const Position: MessageFns<Position> = {
  encode(message: Position, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instrumentId !== "") {
      writer.uint32(10).string(message.instrumentId);
    }
    if (message.quantity !== 0) {
      writer.uint32(17).double(message.quantity);
    }
    if (message.avgPrice !== 0) {
      writer.uint32(25).double(message.avgPrice);
    }
    if (message.unrealizedPnl !== 0) {
      writer.uint32(33).double(message.unrealizedPnl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Position {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePosition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.quantity = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.avgPrice = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.unrealizedPnl = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Position>, I>>(base?: I): Position {
    return Position.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Position>, I>>(object: I): Position {
    const message = createBasePosition();
    message.instrumentId = object.instrumentId ?? "";
    message.quantity = object.quantity ?? 0;
    message.avgPrice = object.avgPrice ?? 0;
    message.unrealizedPnl = object.unrealizedPnl ?? 0;
    return message;
  },
};

function createBasePortfolioSummary(): PortfolioSummary {
  return { totalBalance: 0, availableBalance: 0, pnl: 0 };
}

export const PortfolioSummary: MessageFns<PortfolioSummary> = {
  encode(message: PortfolioSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalBalance !== 0) {
      writer.uint32(9).double(message.totalBalance);
    }
    if (message.availableBalance !== 0) {
      writer.uint32(17).double(message.availableBalance);
    }
    if (message.pnl !== 0) {
      writer.uint32(25).double(message.pnl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PortfolioSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePortfolioSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.totalBalance = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.availableBalance = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.pnl = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PortfolioSummary>, I>>(base?: I): PortfolioSummary {
    return PortfolioSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PortfolioSummary>, I>>(object: I): PortfolioSummary {
    const message = createBasePortfolioSummary();
    message.totalBalance = object.totalBalance ?? 0;
    message.availableBalance = object.availableBalance ?? 0;
    message.pnl = object.pnl ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
