// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: common/portfolio.proto

/* eslint-disable */
import { SignalSide } from "./signal";

export const protobufPackage = "tradingbot.common";

/** Trade represents an executed trade or fill. */
export interface Trade {
  /** trade id */
  id: string;
  /** e.g. "UUID" */
  instrumentId: string;
  side: SignalSide;
  price: number;
  quantity: number;
  /** unix epoch milliseconds */
  timestamp: number;
}

/** Position represents an open position in the portfolio. */
export interface Position {
  /** e.g. "UUID" */
  instrumentId: string;
  /** positive for net long, negative for net short */
  quantity: number;
  /** average entry price */
  avgPrice: number;
  unrealizedPnl: number;
}

/** Portfolio summary contains overall account metrics. */
export interface PortfolioSummary {
  totalBalance: number;
  availableBalance: number;
  pnl: number;
}
