// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: common/instrument.proto

/* eslint-disable */

export const protobufPackage = "tradingbot.common";

export enum AssetClass {
  ASSET_CLASS_UNSPECIFIED = 0,
  CRYPTO = 1,
  STOCK = 2,
  UNRECOGNIZED = -1,
}

export interface Instrument {
  /** Internal unique ID (UUID or generated by Risk Manager) */
  instrumentId: string;
  /** CRYPTO, STOCK, etc. */
  assetClass: AssetClass;
  /** e.g. "BTC/USDT", "GOGL" */
  symbol: string;
  /** e.g. "BINANCE", "NASDAQ", "NYSE", "COINBASE" */
  venue: string;
  /** Exchange-specific ticker, e.g. "BTCUSDT" or "GOGL" */
  externalSymbol: string;
}
