// Auto-generated proto index. Do not edit.
// Generated by scripts/generate-proto-barrel.mjs

export {
  AssetClass,
  Instrument,
  protobufPackage as PROTOBUF_COMMON_PACKAGE,
} from './common/instrument';
export { PortfolioSummary, Position, Trade } from './common/portfolio';
export { Signal, SignalSide } from './common/signal';
export {
  InstrumentRegistered,
  protobufPackage as PROTOBUF_EVENTS_PACKAGE,
} from './events/events';
export {
  GetPortfolioRequest,
  GetPortfolioResponse,
  protobufPackage as PROTOBUF_SERVICES_PORTFOLIO_MANAGER_PACKAGE,
  RegisterInstrumentRequest,
  RegisterInstrumentResponse,
} from './services/portfolio_manager';
export {
  GetLatestSignalsRequest,
  GetLatestSignalsResponse,
  protobufPackage as PROTOBUF_SERVICES_PREDICTION_ENGINE_PACKAGE,
} from './services/prediction_engine';

// Auto-generated grpc constants (inlined).
export const PROTO_FOLDER = 'proto';

export const COMMON_INSTRUMENT_PROTO = 'proto/common/instrument.proto';

export const COMMON_PORTFOLIO_PROTO = 'proto/common/portfolio.proto';

export const COMMON_SIGNAL_PROTO = 'proto/common/signal.proto';

export const EVENTS_EVENTS_PROTO = 'proto/events/events.proto';

export const PORTFOLIO_MANAGER_PROTO = 'proto/services/portfolio_manager.proto';
export const PORTFOLIO_MANAGER_CLIENT = 'PORTFOLIO_MANAGER_CLIENT';

export const PREDICTION_ENGINE_PROTO = 'proto/services/prediction_engine.proto';
export const PREDICTION_ENGINE_CLIENT = 'PREDICTION_ENGINE_CLIENT';
